# Generated by Django 3.1.5 on 2021-08-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
